Wagons
Arshev/rails pull request #1
Opened 2016-10-05 18:01 UTC by Arshev

Я в тупике. Вроде бы все создал для вагонов, но при создании першола и рендеринге его в index.html.erb вылезает ошибка ArgumentError in Wagons#index
Showing /home/erosanin/thinknetica/rails/tutu/app/views/wagons/index.html.erb where line #14 raised:

'nil' is not an ActiveModel-compatible object. It must implement :to_partial_path.

Типа @wagons пустой, что я забыл?) И вообще, таблицы правильно создал? Поля пока без связей, но в принципе на правильном направлении делаю?

2016-10-06 09:08 UTC, vkurennov requested changes
Направление верное, только при компировании будь внимательнее. А еще лучше не копируй, а пиши "с нуля", подглядывая в другие контроллеры как в образец. Ошибок меньше станет и понимание прийдет, а также рука набьется.

2016-10-06 09:08 UTC, vkurennov commented on tutu/app/controllers/wagons_controller.rb
> +    @routes = Wagon.all
Может глючит потому что в контроллере переменная называется @routes, а в виде @wagons? :-)
Если что-то не работает в виде, смотри в соответствующий экшн контроллера.

2016-10-06 09:08 UTC, vkurennov commented on tutu/app/controllers/wagons_controller.rb
> +    @route = Wagon.new
копировать надо не бездумно, а меняя названия переменных и прочее. Тут тоже @wagon должен быть

2016-10-06 09:08 UTC, vkurennov commented on tutu/app/controllers/wagons_controller.rb
> +    if @wagon.save
Тут еще круче. Вагон помещаем в переменную @route, но сохраняем @wagon

2016-10-06 09:08 UTC, vkurennov commented on tutu/app/views/wagons/edit.html.erb
> +<%= form_for(@wagon) do |f| %>
Используй паршл для ошибок, который сделали в прошлом задании

2016-10-06 09:08 UTC, vkurennov commented on tutu/app/views/wagons/index.html.erb
> +    <%= render @wagons if @wagons %>
А в контроллере у тебя @routes

2016-10-06 09:08 UTC, vkurennov commented on tutu/app/views/wagons/new.html.erb
> +<%= form_for(@wagon) do |f| %>
Используй паршл для ошибок

2016-10-06 09:08 UTC, vkurennov commented on tutu/app/views/wagons/new.html.erb
> +<%= form_for(@wagon) do |f| %>
Форма для new и edit одинаковая, вынеси в паршл

2016-10-07 08:46 UTC, vkurennov requested changes
Исправь замечания, залей в эту же ветку и снова сдай на проверку в системе обучения. Новый пулл реквест делать НЕ нужно!

2016-10-07 08:46 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +  <% arr = [] %>
Не считай ничего в видах, выноси это в методы модели и вызывай их тут.

2016-10-07 08:46 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +  <%= arr.size %>
Ну и метод size, он же count есть у ассоциаций, т.е. можно написать так: `@train.wagons.count` и будет тебе счастье

2016-10-07 08:46 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +  <% arr2 = [] %>
Тут тоже можно сделать проще, но пока мы этого не прошли (в след. уроке как раз). Поэтому пока просто сделай в модели Train метод подсчета кол-ва вагонов по типу (метод принимает тип в качестве аргумента) и здесь его вызывай.

2016-10-07 08:46 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +      <% arr2 << wagon %>
Кстати, если нужно только кол-во считать, то не надо объекты в массив помещать, можно же ввести переменую-счетчик и просто на 1 увеличивать внутри цикла.

2016-10-07 08:46 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +  <% arr3 = [] %>
Тут используй метод, о котором я написал выше

2016-10-07 08:46 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +  <% @train.wagons.each do |wagon| %>
Это вынеси в аналогичный метод в модель

2016-10-07 08:46 UTC, vkurennov commented on tutu/app/views/wagons/_form.html.erb
> +  <% if wagon.errors.any? %>
Используй паршл для ошибок из прошлого занятия (common/errors)

2016-10-07 12:18 UTC, Arshev commented on tutu/app/views/trains/show.html.erb
> +  <%= @train.count_wagon('Плацкарт') %>
Ругается на count_wagon.

2016-10-07 13:25 UTC, Arshev commented on tutu/app/views/trains/show.html.erb
> +  <%= @train.count_wagon('Плацкарт') %>
Ругается на wagons в @train.wagons.each do |wagon|

2016-10-08 11:07 UTC, vkurennov requested changes
Если возникает ошибка, пиши какая, это поможет понять, что не так. И сам пробуй ее понять и проанализировать

2016-10-08 11:07 UTC, vkurennov commented on tutu/app/models/train.rb
> +    loop do
Зачем использовать безусловный цикл, когда тут нужен обычный each?

2016-10-08 11:07 UTC, vkurennov commented on tutu/app/models/train.rb
> +    @train.wagons.each do |wagon|
Вот этого достаточно, зачем тут loop?

2016-10-08 11:07 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +  <%= @train.count_wagon('Плацкарт') %>
Вызов верный, метод count_wagon тоже, если loop убрать из него. какая конкретно ошибка возникает?

2016-10-08 11:20 UTC, Arshev commented on tutu/app/views/trains/show.html.erb
> +  <%= @train.count_wagon('Плацкарт') %>
Вот скрин ошибки 
https://yadi.sk/i/qu7_dAUnwTxYZ

2016-10-09 09:21 UTC, vkurennov requested changes
Поправь метод

2016-10-09 09:21 UTC, vkurennov commented on tutu/app/models/train.rb
> +    @train.wagons.each do |wagon|
А, ну так проблема в том, что ты используешь переменную @train, но ведь ее нет. Ты же уже в объекте поезда работаешь, т.е. в самом поезде. @train - это переменная в контроллере и в виде, ты у нее вызываешь метод. А здесь же ты уже в модели, в этом самом методе, т.е. в контексте того объекта, у которого метод вызван, поэтому @train надо заменить на self. И написать sefl.wagons или просто wagons, т.к. self не обязательно указывать, он по-умолчанию подразумевается.

2016-10-09 09:21 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +  <%= @train.count_wagon('Плацкарт') %>
Отписал выше, ошибка не в вызове метода, а в самом методе, в нем же нет уже переменной @train

2016-10-09 12:22 UTC, vkurennov approved these changes
Принято

2016-10-09 15:40 UTC, merged