Wagon STI
Arshev/rails pull request #2
Opened 2016-10-20 18:37 UTC by Arshev

2016-10-21 14:09 UTC, vkurennov requested changes
Исправь замечания

2016-10-21 14:09 UTC, vkurennov commented on tutu/app/models/wagon.rb
> +  validates :set_number, uniqueness: true
Что такое set_number? Это метод, ты пытаешься валидировать метод, поэтому и получаешь ошибку. Валидировать можно только атрибуты

2016-10-21 14:09 UTC, vkurennov commented on tutu/app/models/wagon.rb
> +    self.number_wagon = x + 1
И что тут происходит? Для кажого создаваемого вагона ты сначала присваивашь в х ноль, а потом прибавляешь 1. То есть каждый раз ты к нулю прибавляешь 1. Что будет? Каждый раз ты будешь получать 1. И все вагоны будут с номером 1. Кажется, это не совсем то, что нужно.

2016-10-21 14:09 UTC, vkurennov commented on tutu/db/migrate/20161012170312_add_sort_station_id_to_railway_station_routes.rb
> +    add_column :railway_stations_routes, :sort_station_id, :integer
Почему _id? У тебя же в поле не id  будет храниться, а порядковый номер

2016-10-22 16:28 UTC, Arshev commented on tutu/db/migrate/20161012170312_add_sort_station_id_to_railway_station_routes.rb
> +    add_column :railway_stations_routes, :sort_station_id, :integer
Как теперь это исправить?) Миграция то старая

2016-10-24 08:54 UTC, vkurennov commented on tutu/db/migrate/20161012170312_add_sort_station_id_to_railway_station_routes.rb
> +    add_column :railway_stations_routes, :sort_station_id, :integer
Сделать новую миграцию и в ней переименовать колонку через rename_column

2016-10-24 09:01 UTC, vkurennov requested changes
Исправь замечания

2016-10-24 09:01 UTC, vkurennov commented on tutu/app/models/train.rb
> +  def number_wagon
И что это дает? Во-первых, инстанс-переменная @number видна только внутри модели и только в рамках одного объекта. Не путай их с инстанс-переменными в контроллере, которые еще и в видах доступны. Для моделей это не работает. 
Во-вторых, сам код, по твоем, что делает? Вот он поочередно перебрал все вагоны и номер закинул в @number, а потом ты @number возвращаешь. Т.е. в этой переменнй **всегда** будет номер последнего вагона. Из блока-то ведь данные не возвращаются пока он не завершит свою работу

2016-10-24 09:01 UTC, vkurennov commented on tutu/app/models/train.rb
>     "Верхних: #{place_in_top} Нижних: #{place_in_down}"
Лучше возвращать значения, а не строки. А в строку уже преобразовывать там, где ты это используешь. В данном случае, можно вернуть массив или хеш

2016-10-24 09:01 UTC, vkurennov commented on tutu/app/models/wagon.rb
> +  validates :number_wagon, uniqueness: true
Уникальность в данном случае глобально проверяется, т.е. у 2-х разных поездов не может быть первого вагона. А это неверно. Нужно добавить опцию scope и проверять уникальность в пределах поезда

2016-10-24 09:01 UTC, vkurennov commented on tutu/app/models/wagon.rb
> +    self.number_wagon = Wagon.last.number_wagon + 1
У тебя будут номера глобально устанваливаться. А должны в пределах поезда. Нужно у поезда взять вагон с максимальным номером (это необязательно будет последний, т.к. нумерация может быть с головы) и добавить к нему 1.

2016-10-24 09:01 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +<%= @train.number_wagon %>
И здесь вернется 1 число соответсвующее номеру последнего вагона.

Надо не в модели сделать цикл для перебора вагонов, а здесь и внутри цикла сделать ссылк через link_to, где текстом ссылки будет номер вагона, а значением - ссылка на wagons/show

2016-10-25 17:07 UTC, Arshev commented on tutu/app/views/trains/show.html.erb
> +<%= @train.number_wagon %>
Про циклы в виде вроде говорили что не надо делать, а выносить в модель, или я ошибаюсь?

2016-10-29 16:10 UTC, vkurennov approved these changes
Принято, но исправь замечания

2016-10-29 16:10 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +<%= @train.count_wagon_seats('EconomyWagon') %>
Если у тебя метод возвращает массив, а тебе нужен размер этого массива, то как это сделать? Вызвать у массив метод size: `@train.count_wagon_seats('EconomyWagon').size`

2016-10-29 16:10 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +    <%= link_to wagon.number_wagon, wagon_path %>
Надо вторым аргументом объект wagon передавать или тогда уж `wagon_path(wagon)`, чтобы ссылка была на конкретный вагон

2016-10-29 16:10 UTC, vkurennov commented on tutu/app/views/wagons/index.html.erb
> +   <% @wagons.each do |wagon| %>
можно вместо цикла написать `render @wagons`

2016-10-30 10:40 UTC, Arshev commented on tutu/app/views/trains/show.html.erb
> +<%= @train.count_wagon_seats('EconomyWagon') %>
Так мне же не размер массива нужен, а значения в нем? мне же не кол-во вагонов нужно, а кол-во мест в вагоне, верхних и нижних. Я и хотел сделать тогда массив и в зависимости от типа вагона выводить верхние и нижние места

2016-10-30 10:47 UTC, Arshev commented on tutu/app/views/wagons/index.html.erb
> +   <% @wagons.each do |wagon| %>
Так было то как раз так, но из за разных типов вагонов рельсы паршал ищут с названием типа и ошибка Missing partial coupe_wagons/_coupe_wagon в прошлый раз как раз ты сказал так сделать)

2016-11-01 09:56 UTC, merged

2016-11-02 20:28 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +<%= @train.number_wagon %>
Так это разные циклы. Одно дело реализовывать логику поиска и подсчета, это надо делать в модели, а когда у тебя если коллекция объектов и тебе для каждого надо вывести ссылку, то тут только в виде, ведь ссылки и прочее, что касается интерфейса как раз в виде и формируется

2016-11-02 20:29 UTC, vkurennov commented on tutu/app/views/trains/show.html.erb
> +<%= @train.count_wagon_seats('EconomyWagon') %>
Ну тогда реализвывай метод, который это считатет. И не путем перебора, а используя методы ActiveRecord. Например, where и coun/sum

2016-11-02 20:29 UTC, vkurennov commented on tutu/app/views/wagons/index.html.erb
> +   <% @wagons.each do |wagon| %>
Ок, тогда оставляй как есть