Controllers
Arshev/rails pull request #3
Opened 2016-11-01 15:14 UTC by Arshev

2016-11-05 16:54 UTC, vkurennov requested changes

2016-11-05 16:54 UTC, vkurennov commented on tutu/app/controllers/searches_controller.rb
> +    start_station_id = params[:start_station_id]
Вот где-то тут должен быть вызов метода Search#search_train и  в него мы передаем данные:

`Search.search_train(params[:start_station_id], params[:end_station_id])`

Метод совершает поиск и возвращает массив поездов, а в виде мы уже их выводим

2016-11-05 17:01 UTC, Arshev commented on tutu/app/controllers/searches_controller.rb
> +    start_station_id = params[:start_station_id]
Вроде пробовал так, но нет объекта Search

2016-11-05 20:24 UTC, vkurennov requested changes

2016-11-05 20:24 UTC, vkurennov commented on tutu/app/controllers/searches_controller.rb
> +    Search.search_train(params[:start_station_id], params[:end_station_id])
Метод должен что-то вернуть, а это что-то надо поместить в инстанс-переменную, чтобы потом был доступ к результатам из вида. Посмотри на другие экшены, мы ведь не просто методы вызываем, а еще и результат присваиваем переменным, иначе, как мы доступ к данным в виде получим?

2016-11-05 20:24 UTC, vkurennov commented on tutu/app/models/search.rb
> +    @result = Train.includes(route: :railway_stations).where(railway_stations: { id: start_station_id }) & Train.includes(route: :railway_stations).where(railway_stations: { id: end_station_id })
Эта инстанс-переменная видна только внутри класса Search, не в контроллере, ни в виде она не видна. То есть, тебе надо сделать этот запрос и это и будет результатом работы метода, возвращаемым значением. А присваивать в инстанс-переменную надо в контроллера, т.к. **только инстанс-перемнные контроллера доступны в виде**, потому что вид - это не самостоятельный класс, это как бы "продолжение" контроллера, шаблон, по кторому контроллер создает свой ответ.

2016-11-05 20:26 UTC, vkurennov requested changes

2016-11-05 20:26 UTC, vkurennov commented on tutu/app/models/search.rb
> +class Search < ApplicationRecord
У тебя нет таблицы Search, поэтому не надо наследовать от ApplicationRecord, сделай т.н. PORO-класс (Plain Old Ruby Object), т.е. обычный ruby-класс, без наследования.

2016-11-07 18:31 UTC, vkurennov requested changes

2016-11-07 18:31 UTC, vkurennov commented on tutu/app/controllers/searches_controller.rb
> +    @search_result = Search.search_train(params[:start_station_id], params[:end_station_id])
Вот эти start_station_id и end_station_id и надо вставлять как параметры в ссылку на покупку билета

2016-11-07 18:31 UTC, vkurennov commented on tutu/app/controllers/tickets_controller.rb
> +    @ticket = Ticket.new
Это не в create должно быть, а в new. create - это когда юзер нажмет кнопку "купить", тогда данные будут отправлены в контроллер. А тебе сначала надо форму юзеру показать, поэтому нужен экшн new

2016-11-07 18:31 UTC, vkurennov commented on tutu/app/views/searches/result.html.erb
> +<%= link_to "Купить", new_ticket_path(start_station_id: train.route.railway_stations.first.id, end_station_id: train.route.railway_stations.last.id, train: train.id) %>
Здесь надо использовать params[:start_station_id], как и в контроллере, ведь это именно те значения, который выбрал пользователь.

2016-11-07 18:31 UTC, vkurennov commented on tutu/app/views/searches/show.html.erb
> +  <% @railway_stations.each do |station| %>
Вообще, удобнее, конечно был бы выпадающий список. Кроме того, чекбокс подразумевает возможность выбора нескольких вариантов, а в случае билета, это явно не так.

2016-11-09 18:04 UTC, merged